% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.3 (COMSOL 3.3.0.405, $Date: 2006/08/31 18:03:47 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.3';
vrsn.ext = '';
vrsn.major = 0;
vrsn.build = 405;
vrsn.rcs = '$Name:  $';
vrsn.date = '$Date: 2006/08/31 18:03:47 $';
fem.version = vrsn;

% Geometry
g1=block3('10','10','10','base','corner','pos',{'-5','-5','-5'},'axis',{'0','0','1'},'rot','0');
g2=sphere3('1','pos',{'-2','0','0'},'axis',{'0','0','1'},'rot','0');
g3=sphere3('1','pos',{'2','0','0'},'axis',{'0','0','1'},'rot','0');

% Analyzed geometry
clear s
s.objs={g1,g2,g3};
s.name={'BLK1','SPH1','SPH2'};
s.tags={'g1','g2','g3'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'ConductiveMediaDC';
appl.border = 'on';
appl.assignsuffix = '_dc';
clear bnd
bnd.Jn = {0,1,0};
bnd.type = {'nJ0','dnJ','V0'};
bnd.name = {'Exterior','Ball2','Ball1'};
bnd.ind = [1,1,1,1,1,3,3,3,3,3,3,3,3,2,2,2,2,2,2,2,2,1];
appl.bnd = bnd;
clear equ
equ.sigma = {50,1};
equ.ind = [1,2,2];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'V'}, ...
                  'outcomp',{'V'}, ...
                  'linsolver','cg', ...
                  'prefun','amg');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'slicedata',{'V','cont','internal','unit','V'}, ...
         'slicexspacing',5, ...
         'sliceyspacing',0, ...
         'slicezspacing',0, ...
         'slicemap','jet(1024)', ...
         'title','Slice: Electric potential [V]', ...
         'grid','on', ...
         'campos',[-5.542735441127526,-47.16332692344565,17.12969635674063], ...
         'camtarget',[6.073731576617606,-2.561176486448872,-2.2534373017050466], ...
         'camup',[0.3994085475201614,0.27591354003889923,0.8742679970072322], ...
         'camva',39.5977527090497);

% Integrate
I1=postint(fem,'nJ_dc', ...
           'unit','A', ...
           'dl',[6,7,8,9,10,11,12,13], ...
           'edim',2);

% Integrate
I2=postint(fem,'nJ_dc', ...
           'unit','A', ...
           'dl',[6,7,8,9,10,11,12,13], ...
           'edim',2);
